# Generated by Django 6.1.1 on 2026-09-27 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimCity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DimDistributor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FactDistributorCitySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.dimcity')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.dimdistributor')),
            ],
            options={
                'unique_together': {('distributor', 'city')},
            },
        ),
    ]
